# Generated by Django 5.2.5 on 2026-01-02 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Storage',
                'verbose_name_plural': 'OTP Storage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-uploaded_date']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 2, 1, 52, 58, 391259, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Shift'), ('day', 'Day Shift'), ('evening', 'Evening Shift')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('feedback', 'New Feedback'), ('download', 'Resource Downloaded'), ('purchase', 'Resource Purchased'), ('system', 'System Notification'), ('verification', 'Verification'), ('registration', 'Registration'), ('otp', 'OTP Verification')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('imepay', 'IME Pay'), ('khalti', 'Khalti'), ('demo', 'Demo Payment')], default='esewa', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, choices=[('BIM', 'BIM (Bachelor of Information Management)'), ('BCA', 'BCA (Bachelor of Computer Application)'), ('BBA', 'BBA (Bachelor of Business Administration)'), ('BBM', 'BBM (Bachelor of Business Management)'), ('BBS', 'BBS (Bachelor of Business Studies)'), ('B.Sc.', 'B.Sc. (Bachelor of Science)'), ('BA', 'BA (Bachelor of Arts)'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='verification_type',
            field=models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('student_id', 'Student ID Verification'), ('registration', 'Registration OTP')], max_length=20),
        ),
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_count', models.IntegerField(default=1)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('email', 'ip_address')},
            },
        ),
    ]
