# Generated by Django 5.2.5 on 2026-01-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_created_at'),
    ]

    operations = [
    ]
