# Generated by Django 5.2.5 on 2026-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20260102_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
