# Generated by Django 5.2.5 on 2026-01-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment_khalti_pidx_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_provider_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
