# Generated by Django 5.2.15 on 2026-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_payment_payment_provider_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa')], default='esewa', max_length=20),
        ),
    ]
